<?php

/**
 * @file ParagraphsHelper class
 * Provides functions to create content paragraphs
 */
namespace Drupal\pb_devel_generate\GeneratorHelpers;

use Drupal\paragraphs\Entity\Paragraph;
use Drupal\devel_generate\DevelGenerateBase;
use Drupal\Component\Utility\Random;

class ParagraphsHelper {
  private static function createBaseParagraph($type, $region, $parent_uuid) {
    $default_langcode = \Drupal::service('language_manager')->getDefaultLanguage()->getId();

    $values = [
      'type' => $type,
      'langcode' => $default_langcode,
      'default_langcode' => 1,
    ];

    $paragraph = Paragraph::create($values);

    $behavior_settings = [
      "layout_paragraphs" => [
        "region" => $region,
        "parent_uuid" => $parent_uuid,
        "layout" => "",
        "config" => [],
        "parent_delta" => 0,
      ],
    ];

    $paragraph->setAllBehaviorSettings($behavior_settings);
    return $paragraph;
  }

  public static function createHeadingParagraph($region, $parent_uuid, $code, $label) {
    $paragraph = static::createBaseParagraph('pb_heading', $region, $parent_uuid);
    $paragraph->set('field_pb_identifier', $code);
    $paragraph->set('field_pb_title', $label);

    $paragraph->save();
    return $paragraph;
  }

  public static function createTextParagraph($region, $parent_uuid, $content=null) {
    $paragraph = static::createBaseParagraph('pb_rich_text', $region, $parent_uuid);

    if(is_null($content)) {
      DevelGenerateBase::populateFields($paragraph);
    }
    else {
      $paragraph->field_pb_formatted_text->value = $content;
      $paragraph->field_pb_formatted_text->format = 'basic_html';
    }

    $paragraph->save();
    return $paragraph;
  }

  public static function createCardWithLinkParagraph($region, $parent_uuid, $title, $brief, $preview_image, $style) {
    $paragraph = static::createBaseParagraph('pb_card_with_link', $region, $parent_uuid);

    $paragraph->set('field_pb_abstract', $brief);
    $paragraph->set('field_pb_title', $title);
    $paragraph->set('field_pb_preview_image', $preview_image->id());
    $paragraph->set('field_pb_card_style', $style);
    $paragraph->set('field_pb_link_target', 'https://www.matrushka.com.mx');

    $paragraph->save();
    return $paragraph;
  }

  /**
   * Creates a dummy image paragraph and populates with a random image
   */
  public static function createImageParagraph($region, $parent_uuid) {
    // Create a random media image
    $media_image = MediaHelper::createMediaImage();
    return static::createImageParagraphFromMediaEntity($region, $parent_uuid, $media_image);
  }

  /**
   * Creates an image paragraph from a given media image entity
   */
  public static function createImageParagraphFromMediaEntity($region, $parent_uuid, $media_image) {
    $random = new Random();
    $paragraph = static::createBaseParagraph('pb_image', $region, $parent_uuid);

    $paragraph->set('field_pb_image', $media_image->id());
    // TODO: populate the link target field
    // $paragraph->set('field_pb_link_target', 'http://www.matrushka.com.mx');
    $paragraph->set('field_pb_alt_text', $random->sentences(4));
    $paragraph->save();

    return $paragraph;
  }

  public static function createVideoParagraphFromMediaEntity($region, $parent_uuid, $media_video) {
    $paragraph = static::createBaseParagraph('pb_video', $region, $parent_uuid);
    $paragraph->set('field_pb_video', $media_video->id());
    $paragraph->save();

    return $paragraph;
  }

  // /**
  //  * Creates an URL embed paragraph for the given url
  //  * @param string $url
  //  */
  // public static function createUrlEmbedParagraphFromUrl($region, $parent_uuid, $url) {
  //   $paragraph = static::createBaseParagraph('content_embed_url', $region, $parent_uuid);
  //   $paragraph->set('field_embedded_url', $url);
  //   $paragraph->save();
  //   return $paragraph;
  // }

  /**
   * Creates a Logo Carousel paragraph
   * @param array $images
   *    An array of image paragraphs to be used as logos. If ommitted, a random image set will be created
   */
  public static function createLogoStripParagraph($region, $parent_uuid, $style=null, $images=null) {
    if(!$images) {
      $num_images = mt_rand(10, 20);
      $images = [];
      for($i=0; $i<$num_images; $i++) {
        $images[] = static::createImageParagraph($region, $parent_uuid);
      }
    }

    // Since the entities generated by createBaseParagraph are originally meant to be used with layout paragraphs
    // they have behavior settings that do not apply to the image paragraphs here, such as parent uuid and region
    // Strip the extra behaviors to prevent conflicts
    $field_elements_list = [];
    foreach($images as $image_paragraph) {
      $behavior = $image_paragraph->setAllBehaviorSettings([]);

      $field_elements_list[] = [
        'target_id' => $image_paragraph->id(),
        'target_revision_id' => $image_paragraph->getRevisionId()
      ];
    }

    $paragraph = static::createBaseParagraph('pb_logo_strip', $region, $parent_uuid);
    $paragraph->set('field_pb_logos', $field_elements_list);
    $paragraph->set('field_pb_logo_strip_style', $style);
    $paragraph->save();

    return $paragraph;
  }
}
